# DDoS Auswertung

## Notes:

instead of polars, the polars-lts-cpu package is used, to run on the old CPU's of the mobi8

## Imports

In [19]:
from pathlib import Path
import polars as pl
import matplotlib.pyplot as plt
import pyarrow.parquet as pq

## Globale Parameter

In [20]:
SERVER_IP = "141.22.28.227"

### external IANA protocol list to convert numbers to names

In [21]:
# read IANA list to convert number to text
lf_pro_nb = (
    pl.scan_csv("data/external/protocol-numbers-1.csv", ignore_errors=True)
      .select("Decimal", "Keyword")
).rename({"Keyword": "ip.proto.name", "Decimal": "ip.proto.num"})
lf_pro_nb.head(10).collect()

shape: (10, 2)
┌──────────────┬───────────────┐
│ ip.proto.num ┆ ip.proto.name │
│ ---          ┆ ---           │
│ i64          ┆ str           │
╞══════════════╪═══════════════╡
│ 0            ┆ HOPOPT        │
│ 1            ┆ ICMP          │
│ 2            ┆ IGMP          │
│ 3            ┆ GGP           │
│ 4            ┆ IPv4          │
│ 5            ┆ ST            │
│ 6            ┆ TCP           │
│ 7            ┆ CBT           │
│ 8            ┆ EGP           │
│ 9            ┆ IGP           │
└──────────────┴───────────────┘

In [22]:
# lf = (
#     lf.join(lf_pro_nb, left_on="ip.proto", right_on="ip.proto.num", how="left")
#     .rename({"ip.proto": "ip.proto.num"})
#     .pipe(lambda lf: lf.select(
#     (cols := lf.collect_schema().names(), cols.insert(5, cols.pop(cols.index("ip.proto.name"))), cols)[-1]
# ))
# )

# lf.head(10).collect()

## 1. Überblick über die Daten (raw)

In [23]:
lf = pl.scan_parquet("data/interim/ddos_1/batch_1_2000.parquet")
df_sample = lf.limit(100).collect().sample(10)
df_sample

shape: (10, 35)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.dat ┆ frame.len ┆ frame.pro ┆ ip.src    ┆ … ┆ coap.resp ┆ coap.resp ┆ coap.payl ┆ source_f │
│ etime     ┆ ---       ┆ tocols    ┆ ---       ┆   ┆ onse_to   ┆ onse_in   ┆ oad_lengt ┆ ile      │
│ ---       ┆ i64       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ h         ┆ ---      │
│ datetime[ ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│ μs]       ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-08-1 ┆ 1514      ┆ eth:ether ┆ 27.124.68 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ .194      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574079  ┆           ┆ dp:snmp   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1514      ┆ eth:ether ┆ 83.221.17 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 9.204     ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.573754  ┆           ┆ dp:cldap  ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 861       ┆ eth:ether ┆ 113.160.2 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:d ┆ 34.49     ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.573915  ┆           ┆ ata       ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 786       ┆ eth:ether ┆ 208.77.17 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 9.64      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574189  ┆           ┆ dp:snmp   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1514      ┆ eth:ether ┆ 200.41.17 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:d ┆ 4.22      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.573601  ┆           ┆ ata       ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1514      ┆ eth:ether ┆ 38.52.217 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:d ┆ .173      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574188  ┆           ┆ ata       ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1506      ┆ eth:ether ┆ 116.106.1 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:d ┆ 97.147    ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.573859  ┆           ┆ ata       ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 778       ┆ eth:ether ┆ 208.77.17 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:d ┆ 9.64      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574189  ┆           ┆ ata       ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1506      ┆ eth:ether ┆ 82.79.235 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ .118      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574454  ┆           ┆ dp:dns    ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1514      ┆ eth:ether ┆ 185.90.73 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:d ┆ .33       ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574236  ┆           ┆ ata       ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
double_ip = lf.filter(
    pl.col("ip.ttl").str.contains(",") | pl.col("ip.proto").str.contains(",")
).collect()
print(double_ip.shape)
print(double_ip)

double_ports = lf.filter(
    pl.col("udp.dstport").str.contains(",") | pl.col("udp.srcport").str.contains(",") | pl.col("tcp.dstport").str.contains(",") | pl.col("udp.srcport").str.contains(",")
).collect()
print(double_ports.shape)
print(double_ports)

(13312618, 35)
shape: (13_312_618, 35)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.dat ┆ frame.len ┆ frame.pro ┆ ip.src    ┆ … ┆ coap.resp ┆ coap.resp ┆ coap.payl ┆ source_f │
│ etime     ┆ ---       ┆ tocols    ┆ ---       ┆   ┆ onse_to   ┆ onse_in   ┆ oad_lengt ┆ ile      │
│ ---       ┆ i64       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ h         ┆ ---      │
│ datetime[ ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│ μs]       ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-08-1 ┆ 70        ┆ eth:ether ┆ 186.9.151 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:i ┆ .108,141. ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574617  ┆           ┆ cmp:ip:ud ┆ 22.28.227 ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ p         ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 164       ┆ eth:ether ┆ 213.229.2 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:i ┆ 41.118,14 ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.707449  ┆           ┆ cmp:ip:ud ┆ 1.22.28.2 ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ p:s…      ┆ 27        ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 164       ┆ eth:ether ┆ 105.106.7 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:i ┆ 2.193,141 ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.707877  ┆           ┆ cmp:ip:ud ┆ .22.28.22 ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ p:s…      ┆ 7         ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 74        ┆ eth:ether ┆ 213.161.1 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:i ┆ 89.75,141 ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.712003  ┆           ┆ cmp:ip:ud ┆ .22.28.22 ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ p:d…      ┆ 7         ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 74        ┆ eth:ether ┆ 1.29.78.1 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:i ┆ 83,141.22 ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.718220  ┆           ┆ cmp:ip:ud ┆ .28.227   ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ p:d…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-08-1 ┆ 590       ┆ eth:ether ┆ 141.22.28 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:ip:i ┆ .227,111. ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 5.911970  ┆           ┆ cmp:ip:ud ┆ 3.52.138  ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ p:c…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 433       ┆ eth:ether ┆ 141.22.28 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:ip:i ┆ .227,190. ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 5.911973  ┆           ┆ cmp:ip:ud ┆ 204.230.2 ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ p:d…      ┆ 8         ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 388       ┆ eth:ether ┆ 141.22.28 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:ip:i ┆ .227,102. ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 5.911976  ┆           ┆ cmp:ip:ud ┆ 152.165.2 ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ p:d…      ┆ 54        ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 555       ┆ eth:ether ┆ 141.22.28 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:ip:i ┆ .227,203. ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 5.911980  ┆           ┆ cmp:ip:ud ┆ 150.154.1 ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ p:d…      ┆ 42        ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 70        ┆ eth:ether ┆ 192.30.13 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:ip:i ┆ 3.66,141. ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 5.916684  ┆           ┆ cmp:ip:ud ┆ 22.28.227 ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ p         ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘
(0, 35)
shape: (0, 35)
┌────────────┬───────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ frame.date ┆ frame.len ┆ frame.prot ┆ ip.src ┆ … ┆ coap.resp ┆ coap.resp ┆ coap.payl ┆ source_fi │
│ time       ┆ ---       ┆ ocols      ┆ ---    ┆   ┆ onse_to   ┆ onse_in   ┆ oad_lengt ┆ le        │
│ ---        ┆ i64       ┆ ---        ┆ str    ┆   ┆ ---       ┆ ---       ┆ h         ┆ ---       │
│ datetime[μ ┆           ┆ str        ┆        ┆   ┆ str       ┆ str       ┆ ---       ┆ str       │
│ s]         ┆           ┆            ┆        ┆   ┆           ┆           ┆ str       ┆           │
╞════════════╪═══════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
└────────────┴───────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Datenübersicht

#### Incoming vs. Outgoing

In [25]:
def split_direction(lf: pl.LazyFrame, server_ip):
    lf_out = lf.filter(pl.col("ip.src") == server_ip)
    lf_in = lf.filter(pl.col("ip.dst") == server_ip)
    lf_null = lf.filter(
        (pl.col("ip.dst") != server_ip) & (pl.col("ip.src") != server_ip)
    )
    lf_null = lf.filter(
        pl.col("ip.src").is_null() | pl.col("ip.dst").is_null()
    )
    
    return lf_out, lf_in, lf_null

In [26]:
lf_out, lf_in, lf_null = split_direction(lf, SERVER_IP)

size = lf.select(pl.len()).collect().item()
size_out = lf_out.select(pl.len()).collect().item()
size_in = lf_in.select(pl.len()).collect().item()
size_null = lf_null.select(pl.len()).collect().item()

print(f"Packets gesamt:{size:3,}\n")
print(f"Anteil out: {size_out/size:.6}%")
print(f"Packets out:", size_out)
print(f"Anteil in: {size_in/size:.2}%")
print(f"Packets in:", size_in)
print(f"Anteil null: {size_null / size:.6f}%")
print(f"Packets null:", size_null)

Packets gesamt:1,392,529,795

Anteil out: 5.92662e-06%
Packets out: 8253
Anteil in: 0.99%
Packets in: 1379179843
Anteil null: 0.000020%
Packets null: 27831

#### Transport Protokoll

In [27]:
def split_transport(lf: pl.LazyFrame) -> tuple[pl.LazyFrame, ...]:
    protos = lf.select("ip.proto").unique().collect()["ip.proto"].to_list()
    return tuple(
        lf.filter(
            pl.col("ip.proto").is_null() if proto is None
            else pl.col("ip.proto") == proto
        )
        for proto in protos
    )

In [28]:
lf_by_proto = (
    lf.group_by("ip.proto")
    .agg(pl.len().alias("count"))
    .collect()
    .sort("count", descending=True)
)

In [29]:
total_packets: int  = lf.select(pl.len()).collect().item()
total_bytes: int = lf.select(pl.col("frame.len").sum()).collect().item()

t_start = lf.select(pl.col("frame.datetime").min()).collect().item()
t_end = lf.select(pl.col("frame.datetime").max()).collect().item()
if t_start and t_end != None:
    duration_s = (t_end - t_start).total_seconds()

print(f"Pakete gesamt : {total_packets:>12}")
print(f"Bytes gesamt  : {total_bytes:>12,}  ({total_bytes/1e6:.1f} MB)")
print(f"Zeitraum      : {t_start}  →  {t_end}")
print(f"Dauer         : {duration_s:.1f} s")
print(f"Ø Paketrate   : {total_packets/duration_s:>10,.1f} pkt/s")
print(f"Ø Bitrate     : {total_bytes*8/duration_s/1e6:>10,.1f} Mbit/s")

Pakete gesamt :   1392529795
Bytes gesamt  : 1,599,893,232,333  (1599893.2 MB)
Zeitraum      : 2025-08-13 15:51:49.573544  →  2025-08-13 19:39:55.926376
Dauer         : 13686.4 s
Ø Paketrate   :  101,745.9 pkt/s
Ø Bitrate     :      935.2 Mbit/s

#### Top-Talker (meiste Pakete / meiste Bytes)

In [30]:
talkers = (
    lf.group_by("ip.src")
    .agg([
        pl.len().alias("packets"),
        pl.col("frame.len").sum().alias("bytes"),
    ])
    .sort("bytes", descending=True)
)
top_talkers = talkers.head(20).collect()
top_talkers

shape: (20, 3)
┌─────────────────┬─────────┬────────────┐
│ ip.src          ┆ packets ┆ bytes      │
│ ---             ┆ ---     ┆ ---        │
│ str             ┆ u32     ┆ i64        │
╞═════════════════╪═════════╪════════════╡
│ 163.181.207.4   ┆ 4061910 ┆ 1957840620 │
│ 163.181.207.2   ┆ 4053211 ┆ 1953647702 │
│ 163.181.207.1   ┆ 4051925 ┆ 1953027850 │
│ 163.181.207.3   ┆ 3876695 ┆ 1868566990 │
│ 195.69.189.18   ┆ 3766660 ┆ 1815530120 │
│ …               ┆ …       ┆ …          │
│ 201.62.49.58    ┆ 1531489 ┆ 738177698  │
│ 124.120.113.203 ┆ 1442965 ┆ 695509130  │
│ 217.73.144.39   ┆ 1379396 ┆ 664868872  │
│ 111.68.102.2    ┆ 1316314 ┆ 634427276  │
│ 121.1.3.5       ┆ 1235046 ┆ 595292172  │
└─────────────────┴─────────┴────────────┘

In [31]:
lf_ipv6 = lf.filter(
    pl.col("ipv6.src").is_not_null() | pl.col("ipv6.dst").is_not_null()
).collect()
lf_ipv6

shape: (7_841, 35)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.dat ┆ frame.len ┆ frame.pro ┆ ip.src    ┆ … ┆ coap.resp ┆ coap.resp ┆ coap.payl ┆ source_f │
│ etime     ┆ ---       ┆ tocols    ┆ ---       ┆   ┆ onse_to   ┆ onse_in   ┆ oad_lengt ┆ ile      │
│ ---       ┆ i64       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ h         ┆ ---      │
│ datetime[ ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│ μs]       ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-08-1 ┆ 1374      ┆ eth:ether ┆ 106.8.207 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:5 ┆           ┆ type:ip:u ┆ .199      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 1.835864  ┆           ┆ dp:teredo ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ :ip…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 191       ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:5 ┆           ┆ type:vlan ┆           ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 2.796131  ┆           ┆ :ethertyp ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ e:i…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 191       ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:5 ┆           ┆ type:vlan ┆           ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 7.292536  ┆           ┆ :ethertyp ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ e:i…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 162       ┆ eth:ether ┆ 181.199.1 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:5 ┆           ┆ type:ip:u ┆ 19.134    ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 7.478403  ┆           ┆ dp:amt:ip ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ :ip…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 191       ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:5 ┆           ┆ type:vlan ┆           ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 8.479987  ┆           ┆ :ethertyp ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ e:i…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-08-1 ┆ 191       ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:4 ┆           ┆ type:vlan ┆           ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 3.326595  ┆           ┆ :ethertyp ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ e:i…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1374      ┆ eth:ether ┆ 117.176.2 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:4 ┆           ┆ type:ip:u ┆ 12.114    ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 4.179940  ┆           ┆ dp:teredo ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ :ip…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1506      ┆ eth:ether ┆ 14.185.17 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:4 ┆           ┆ type:ip:u ┆ 1.4       ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 8.173609  ┆           ┆ dp:mpls:i ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ pv6…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 202       ┆ eth:ether ┆ 59.164.64 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:ip:u ┆ .131      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 1.328010  ┆           ┆ dp:mpls:i ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ pv6…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 191       ┆ eth:ether ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:vlan ┆           ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 2.203539  ┆           ┆ :ethertyp ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆ e:i…      ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [32]:
lf_coap = lf.filter(
    pl.col("coap.version").is_not_null()
).collect()
lf_coap

shape: (108_085_505, 35)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ frame.dat ┆ frame.len ┆ frame.pro ┆ ip.src    ┆ … ┆ coap.resp ┆ coap.resp ┆ coap.payl ┆ source_f │
│ etime     ┆ ---       ┆ tocols    ┆ ---       ┆   ┆ onse_to   ┆ onse_in   ┆ oad_lengt ┆ ile      │
│ ---       ┆ i64       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ h         ┆ ---      │
│ datetime[ ┆           ┆ str       ┆           ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│ μs]       ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-08-1 ┆ 1374      ┆ eth:ether ┆ 218.57.3. ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 179       ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.573815  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1335      ┆ eth:ether ┆ 183.141.1 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 75.241    ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.573971  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1219      ┆ eth:ether ┆ 111.50.9. ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 66        ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574021  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1335      ┆ eth:ether ┆ 111.38.22 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 0.83      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574340  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1506      ┆ eth:ether ┆ 122.231.2 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 15:51:4 ┆           ┆ type:ip:u ┆ 54.74     ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 9.574506  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025-08-1 ┆ 1514      ┆ eth:ether ┆ 115.45.28 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:ip:u ┆ .90       ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 5.925889  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1335      ┆ eth:ether ┆ 115.224.2 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:ip:u ┆ 29.102    ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 5.926098  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1490      ┆ eth:ether ┆ 112.6.176 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:ip:u ┆ .207      ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 5.926209  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1374      ┆ eth:ether ┆ 183.233.1 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:ip:u ┆ 31.45     ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 5.926316  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
│ 2025-08-1 ┆ 1374      ┆ eth:ether ┆ 112.27.20 ┆ … ┆ null      ┆ null      ┆ null      ┆ data/raw │
│ 3 19:39:5 ┆           ┆ type:ip:u ┆ 8.158     ┆   ┆           ┆           ┆           ┆ /ddos_1/ │
│ 5.926376  ┆           ┆ dp:coap   ┆           ┆   ┆           ┆           ┆           ┆ 13082025 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _DDOS_…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [33]:
lf_dtls = lf.filter(
    pl.col("dtls.record.content_type").is_not_null() | pl.col("dtls.record.version").is_not_null() | pl.col("dtls.handshake.type").is_not_null()
).collect()
lf_dtls

shape: (0, 35)
┌────────────┬───────────┬────────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ frame.date ┆ frame.len ┆ frame.prot ┆ ip.src ┆ … ┆ coap.resp ┆ coap.resp ┆ coap.payl ┆ source_fi │
│ time       ┆ ---       ┆ ocols      ┆ ---    ┆   ┆ onse_to   ┆ onse_in   ┆ oad_lengt ┆ le        │
│ ---        ┆ i64       ┆ ---        ┆ str    ┆   ┆ ---       ┆ ---       ┆ h         ┆ ---       │
│ datetime[μ ┆           ┆ str        ┆        ┆   ┆ str       ┆ str       ┆ ---       ┆ str       │
│ s]         ┆           ┆            ┆        ┆   ┆           ┆           ┆ str       ┆           │
╞════════════╪═══════════╪════════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
└────────────┴───────────┴────────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘